##### BEGIN external-mapped/Dockerfile/image-header #####
FROM confluentinc/cp-enterprise-control-center:6.0.0
##### END external-mapped/Dockerfile/image-header #####

##### BEGIN image/Dockerfile/build-instructions #####
USER root
RUN yum install -y gettext && \
    yum install -y jq && \
    rm -rf /var/cache/yum/*
##### END image/Dockerfile/build-instructions #####

##### BEGIN external/Dockerfile/conteco #####
COPY ./ /conteco/repo/
##### END external/Dockerfile/conteco #####

##### BEGIN external-mapped/Dockerfile/labels-footer #####
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="external" \
      io.vcweb.name="confluent_cc" \
      io.vcweb.tag="6.0.0" \
      io.vcweb.base="confluentinc/cp-enterprise-control-center:6.0.0" \
      io.vcweb.build="external-mapped" \
      io.vcweb.label="external.confluent_cc - ContEco" \
      io.vcweb.description="Confluent Control Center image with ContEco external prerequisites installed." \
      io.vcweb.repository="/conteco/repo"
##### END external-mapped/Dockerfile/labels-footer #####
