#!/usr/bin/env bash

export CONTECO_LABEL="external.confluent_cc - ContEco"
export CONTECO_DESCRIPTION="Confluent Control Center image with ContEco external prerequisites installed."

export CONTECO_TYPE="external"
export CONTECO_NAME="confluent_cc"
export CONTECO_TAG="6.0.0"

export CONTECO_BASE="confluentinc/cp-enterprise-control-center:6.0.0"
export CONTECO_BUILD="external-mapped"
