#!/usr/bin/env bash

export CONTECO_LABEL="external.confluent-cc - ContEco"
export CONTECO_DESCRIPTION="Confluent Control Center image with ContEco external prerequisites installed."

export CONTECO_TYPE="external"
export CONTECO_NAME="confluent-cc"
export CONTECO_TAG="5.4.0"

export CONTECO_BASE="confluentinc/cp-enterprise-control-center:5.4.0"
export CONTECO_BUILD="external-mapped"
